stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
      --destination "${CI_REGISTRY_IMAGE}:latest"
      --build-arg BACKEND_URL=${BACKEND_URL}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build-backend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile.backend"
      --destination "${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_SHORT_SHA}"
      --destination "${CI_REGISTRY_IMAGE}/backend:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy:
  stage: deploy
  image: rancher/curlimages-curl:7.73.0
  script: 
    - curl -X POST https://portainer.sifs0005.infs.ch/api/webhooks/6084e6a7-455b-49ec-90de-9c300e7ea50a # frontend
    - curl -X POST https://portainer.sifs0005.infs.ch/api/webhooks/f9379a5e-6af4-4a33-aede-88ca220ee92b # backend
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH